// web-frontend/app.vue
<template>
  <div>
    <h1>Movie Knight</h1>
    <ul>
      <li v-for="genre in genres" :key="genre.id">
        {{genre.name}}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
export default {
  data() {
    return {
      genresFetched: false,
      genres: []
    }
  },
  mounted() {
    if (!this.genresFetched) {
      fetch('http://localhost:3000/api/genres')
        .then(async(r) => {
          const result = await r.json()
          this.genresFetched = true
          this.genres = result.genres
        })
        .catch(e => {
          console.error('Error fetching genres:', e);
          this.genresFetched = true
        })
    }
  }
};
</script>

// web-fe/src/App.tsx
import './App.css'

import { useEffect } from 'react'

function App() {

  useEffect(() => {
    fetch('rest_api/movies?genres=88c18939-389d-485c-8b25-9150c7a4b321') // Use the service name as the hostname
    .then((response) => {
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      return response.json();
    })
    .then((data) => {
      console.log('Parsed JSON:', data);
    })
    .catch((error) => {
      console.error('FETCH ERROR:', error);
    });
  }, [])

  return (
    <>
      <div>
        <p>Movie Knight App</p>
      </div>
    </>
  )
}

export default App
